os: linux
language: cpp
compiler: gcc

jobs:
    include:
      - name: "CentOS 8"
        env: OS=el DIST=8
      - name: "Ubuntu Disco"
        env: OS=ubuntu DIST=disco

install:
  - curl -L https://tarantool.io/installer.sh | VER=2.2 sudo -E bash

script:
  - make -j4
  - make test
